# PDFlib bindings Makefile
# $Id: Makefile,v 1.7 2004/12/13 18:28:26 kurt Exp $

include ../../config/mkcommon.inc

SUB_DIRS =  $(BINDINGS)

include ../../config/mksubdirs.inc


clean::
	$(RM) php/smoke_c*.trace php/smoke_c*.pdf
	$(RM) rpg/smoke_c*.trace rpg/smoke_c*.pdf
