# Generated automatically from Makefile.in by configure.
# Main libs Makefile
# $Id: Makefile,v 1.34.16.1 2007/04/30 07:39:56 rjs Exp $

# keep the order, some libs have to be build before others

include ../config/mkcommon.inc

SUB_DIRS = $(LIBTARGETS)

include ../config/mksubdirs.inc
